name: API TEST FRAMEWORK

on:
  push:
    branches: [ "JSAPIAUTOMATIONMASTER" ]
  pull_request:
    branches: [ "JSAPIAUTOMATIONMASTER" ]
  schedule:
    - cron: 00 18 * * *
    - cron: 00 3 * * * 
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      if : always()
   
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
   
    - name: Execute Test
      run: mvn clean test -Dsuite=testng
    
    - name: Upload a build artifacts
      if : always()
      uses: actions/upload-artifact@v6.0.0
      with: 
       name: Logs
       path: logs/

    - name: Publish Test Report
      if: always()
      uses: turing85/publish-report@v2.3.0
      with:
        name: TestNG Results
        path: /APIAutomationFramework/test-output/junitreports/TEST-*.xml
        reporter: java-junit
      
